### ISSUE TITLE
Error when syncing: cannot unmarshal object into Go struct field Board.panels

### ISSUE THREAD

**Issue by telmich** [mpostument/grafana-sync#43]
Using grafana-sync I receive this error on a specific dashboard:

```
/ # grafana-sync pull-dashboards --apikey="..." --directory=dashboards --url https://emonitor1.place6.ungleich.ch
2022/02/05 12:08:18 unmarshal board: json: cannot unmarshal object into Go struct field Board.panels of type string for db/uplink-monitoring-2022
```

Does it help if I paste the dashboard json in here?

**Comment by mpostument** [comment]
This is an issue with grafana SDK itself. I have opened an issue here https://github.com/grafana-tools/sdk/issues/130. But it is not resolved yet. Can you upvote the issue there? Maybe it will speed up process

**Comment by mpostument** [comment]
This error theoretically should be fixed once generics are released https://github.com/grafana-tools/sdk/pull/190#issuecomment-1022983930

**Comment by telmich** [comment]
I was wondering if there is any progress now that the https://github.com/grafana-tools/sdk/pull/190 has been merged?

**Comment by mpostument** [comment]
I will deploy new version today

**Comment by mpostument** [comment]
The new version is built - https://github.com/mpostument/grafana-sync/releases/tag/1.4.7
Please check if this will solve you issue

**Comment by bixu** [comment]
We are still seeing this error with the 1.7.0 release. For example:
```
2024/02/22 15:47:33 unmarshal board: json: cannot unmarshal object into Go struct field Target.targets.groupBy of type string (panel "CPU usage/s for $instance" of type "graph") (panel "Resources" of type "row") for db/alertmanager
2024/02/22 15:47:35 unmarshal board: json: cannot unmarshal object into Go struct field Target.targets.tags of type []struct { Key string "json:\"key,omitempty\""; Operator string "json:\"operator,omitempty\""; Value string "json:\"value,omitempty\"" } (panel "Global Samples Sent by Remote" of type "timeseries") for db/prometheus-remote-storage-stats
```

CC @BouchaaraAdil

**Comment by BouchaaraAdil** [comment]
i have synced that dashboard from my local machine and I didn't see any difference it's  working
the warnings you stated are already filled in a [GitHub issue](https://github.com/mpostument/grafana-sync/issues/6#issuecomment-1948184832)
we can test apply it for only for Squad-Observability (Observability is a backup) till we validate that's working perfectly
in the meantime we open a ticket for the warnings and we follow up maybe opening a PR to fix it

**Comment by BouchaaraAdil** [comment]
@bixu i added a coment last week already here https://github.com/mpostument/grafana-sync/issues/6#issuecomment-1948184832
